version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/efortin/kubectl-auth-vault
